on:
  push:
    branches:
     - main
     - master
     - test-pkgdown # rm this
  pull_request:
    branches:
     - main
     - master

name: pkgdown

jobs:
  pkgdown:
    if: ${{ github.event_name == 'push' || startsWith(github.head_ref, 'pkgdown/') }}
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-tinytex@v1
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX

      - name: Install pak and query dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps(".", dependencies = TRUE), ".github/r-depends.rds")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.R_LIBS_USER }}/*
            !${{ env.R_LIBS_USER }}/pak
          key: macos-latest-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: macos-latest-${{ steps.install-r.outputs.installed-r-version }}-1-

      - name: Install package and dependencies
        run: |
          pak::local_install_dev_deps(upgrade = TRUE, dependencies = c("all", "Config/Needs/website"))
          pak::pkg_install("r-lib/pkgdown")
          pak::pkg_install("rstudio/quillt")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Cache some pkgdown assets
        uses: actions/cache@v2
        with:
          path: |
            vignettes/articles/resources/*.gif
            vignettes/articles/resources/*.pdf
            vignettes/articles/cache/*.rds
          key: 2-${{ hashFiles('vignettes/articles/_child_examples.Rmd') }}-${{ github.sha }}
          restore-keys: |
            2-${{ hashFiles('vignettes/articles/_child_examples.Rmd') }}-
            2-

      - name: Build pkgdown site
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
